version: '3.8'

services:
  backend:
    depends_on:
      - 'mongo'
      - 'minio'
    environment:
      NODE_ENV: ${NODE_ENV}
      IINE_DATABASE: ${MONGO_INITDB_DATABASE}
      IINE_DB_UERNAME: ${MONGO_IINE_UERNAME}
      IINE_DB_PASSWORD: ${MONGO_IINE_PASSWORD}
      BUCKET_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      BUCKET_SECRET_KEY: ${MINIO_SECRET_KEY}
    build: ./backend
    tty: true
    stdin_open: true
    ports:
      - '3003:3003'
    volumes:
      - './backend:/app'
  
  mongo:
    image: 'mongo:5.0'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_IINE_UERNAME: ${MONGO_IINE_UERNAME}
      MONGO_IINE_PASSWORD: ${MONGO_IINE_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - ./tmp/mongo/db:/data/db
      - ./tmp/mongo/configdb:/data/configdb

  minio:
    image: 'minio/minio'
    command: minio server /tmp/minio --address :9000 --console-address :9001
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./tmp/minio:/tmp/minio
